build:
  image: alpine
  only:
      - gitlab_ci
  tags:
      - docker_backend_runner
  before_script:
      - apk add openssh-client
      - eval  $(ssh-agent -s)
      - mkdir -p ~/.ssh
      - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_rsa
      - chmod 600 ~/.ssh
      - ls -la ~/.ssh
      - cat ~/.ssh/id_rsa
  script:
      - echo "Test"
