build:
  image: alpine
  only:
      - gitlab_ci
  tags:
      - docker_backend_runner
  before_script:
      - apk add openssh-client
      - eval  $(ssh-agent -s)
      - mkdir -p ~/.ssh
      - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
  script:
      - ssh -o StrictHostKeyChecking=no $SSH_HOST "cd $REMOTE_PATH && pwd"
      - ssh -o StrictHostKeyChecking=no $SSH_HOST "cd $REMOTE_PATH && git pull origin gitlab_ci"
 #     - ssh -o StrictHostKeyChecking=no $SSH_HOST "cd $REMOTE_PATH && source ~/.bashrc && nvm use 16.6.2 && npm install"
#      - ssh -o StrictHostKeyChecking=no $SSH_HOST "cd $REMOTE_PATH && nvm use v21.7.2 && npm install"
      - ssh -o StrictHostKeyChecking=no $SSH_HOST "cd $REMOTE_PATH && npm install"
      - ssh -o StrictHostKeyChecking=no $SSH_HOST "cd $REMOTE_PATH && npm run build"
      - ssh -o StrictHostKeyChecking=no $SSH_HOST "echo "Операция успешно проведена!" "
      - exit_code=$?
